#include "nsISupports.idl"
[scriptable, uuid(f76b2347-aea1-483d-861b-06b392bfa38f)]
interface mhIHeader : nsISupports
{
	attribute string  action;
	attribute string  name;
	attribute string  value;
  attribute string  comment;
	attribute boolean enabled;
	attribute boolean selected;
	
	boolean equals(in mhIHeader obj);
};
