#include "nsISupports.idl"

interface mhIHeader;

[scriptable, uuid(1bb30833-e65f-492a-b8eb-9422b69716c7)]
interface nsIModifyResponseHeaders : nsISupports
{
    attribute unsigned long count;
    attribute boolean active;
    attribute boolean openAsTab;
    attribute boolean windowOpen;

    string getHeaders();
    void saveHeaders(in string headersJSON);
};
